### ISSUE TITLE
Unclear description of "Step 3 - Add Collaborator in Github"

### ISSUE THREAD

**Issue by michaelkubina** [RabeaMue/2021-11-29-Data_Librarian#1]
In the description of Modul_1/Git/Eigenes_Git_Repo_fuer_den_Kurs_einrichten.md theres the text:

"Füge deine Gruppenmitglieder, Konrad (GitHub-Name: konrad) und Rabea (GitHub-Name: RabeaMue) als Collaborator auf GitHub hinzu:
**"Settings" > "Collaborators"** und dort den Nutzernamen eingeben."

Neither the "Settings" reachable from your profile picture nor the "Settings" reachable from the menu in your current repo (next to Insights) offer such a entrypoint.

Is it possible, that you meant "Settings > Manage Access > Add people" instead?

With best regards,
Michael

**Comment by RabeaMue** [comment]
@michaelkubina thanks for mentioning! 
Fixed it with your suggestion.

Best
Rabea
